version: '3'

services:
  frontend:
    build: ./FrontEnd
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    networks:
      - frontend-backend

  backend:
    build: ./BackEnd
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - frontend-backend

networks:
  frontend-backend:
    driver: bridge